Config = {}
Config.Locale = 'en'
Config.DebugLog = true
Config.LimitToAmbulanceJob = false

Config.DelayPedSpawnUntilPlayerNearby = true -- Maybe a workaround for OneSync issues with ped spawning?
Config.DelayPedSpawnDistance = 60

Config.AmbulanceModels = {
    {model = 'AMBMED', maxPatientsPerTrip = 3},
    {model = 'AMBMED2', maxPatientsPerTrip = 3},
    {model = 'AMBMED3', maxPatientsPerTrip = 3},
    {model = 'AMBMED4', maxPatientsPerTrip = 3},
    {model = 'AMBMED5', maxPatientsPerTrip = 1},
    {model = 'AMBMED6', maxPatientsPerTrip = 2},
}

Config.ActivationKey = 56
Config.ActivationKeyText = 'INPUT_CONTEXT'

Config.InitialSeconds = 300
Config.MaxLevels = 3

Config.Formulas = {
    moneyPerLevel               = function(level)                   return 50 * level * level end,
    additionalTimeForPickup     = function(distanceFromHospital)    return math.floor(distanceFromHospital / 15) end,
    additionalTimeForDropOff    = function(numberOfPatients)        return 15 * numberOfPatients end,
    timeLostForDamage           = function(damage)                  return math.floor(damage) end,
}

Config.PedEndInvincibilityDistance = 30.0
Config.PedPickupDistance = 10.0
Config.EnterVehicleTimeout = 10000
Config.Markers = {
    Size = 10.0,
}

Config.Sounds = {
    failedMission = {
        audioRef = 'MissionFailedSounds', 
        audioName = 'ScreenFlash'
    },
    passedMission = {
        audioRef = 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS',
        audioName = 'Mission_Pass_Notify'
    },
    timeAdded = {
        audioRef = 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS',
        audioName = 'Hack_Success'
    },
    timeRemoved = {
        audioRef = 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS',
        audioName = 'Hack_Failed'
    }
}

Config.MaxSpawnPointDistanceAllowedFromHospital = 2400 -- used to check that you didn't forget a - in a coordinate below or accidentally enter a paleto spawn location in for metro los santos :|

Config.Hospitals = {
       {
        name = 'Paleto',
        x = -52.00,
        y = 6528.30,
        z = 30.48,
        spawnPoints = {
            {x = 407.41, y = 6494.75, z = 28.79},              {x = -711.17, y = 5756.36, z = 17.85},
            {x = 103.23, y = 6369.79, z = 32.71},              {x = -72.29, y = 6268.06, z = 32.41},   
            {x = -271.80, y = 6070.65, z = 32.46},             {x = -425.02, y = 6025.45, z = 32.63},   
            {x = -206.54, y = 6552.64, z = 11.99},             {x = -697.89, y = 5809.62, z = 18.76},   
            {x = -562.16, y = 5352.13, z = 71.40},             {x = -1579.42, y = 5171.02, z = 20.88},   
            {x = -1633.60, y = 4724.24, z = 54.30},            {x = -801.20, y = 5412.02, z = 36.07},    
            {x = -320.51, y = 6075.45, z = 32.54},             {x = -140.47, y = 6198.77, z = 33.23},   
            {x = -86.50, y = 6352.35, z = 32.75},              {x = 1685.24, y = 6424.98, z = 33.71},
            {x = 1481.52, y = 6416.62, z = 22.94},             {x = -249.79, y = 6064.69, z = 31.70},
            {x = -598.53, y = 5008.11, z = 142.71},

        }
    },
{
        name = 'Sandy',
        x = 1826.98,
        y = 3693.56,
        z = 34.21,
        spawnPoints = {
            {x = 2404.20, y = 5021.12, z = 46.12},              {x = 1498.06, y = 3578.47, z = 35.26},
            {x = 2244.23, y = 5171.69, z = 59.64},              {x = 1523.27, y = 3769.01, z = 34.04},   
            {x = 1933.04, y = 5175.54, z = 47.37},             {x = 1696.37, y = 3774.79, z = 34.73},   
            {x = 1910.61, y = 4934.14, z = 48.90},             {x = 1925.45, y = 3884.30, z = 32.34},   
            {x = 2629.43, y = 4642.77, z = 34.14},             {x = 1980.68, y = 3704.71, z = 32.38},   
            {x = 2607.28, y = 4951.84, z = 40.65},            {x = 1694.08, y = 3454.25, z = 36.84},    
            {x = 699.27, y = 4214.18, z = 50.99},             {x = 1688.28, y = 3222.42, z = 40.68},   
            {x = 107.93, y = 4519.78, z = 90.32},              {x = 1501.71, y = 3073.96, z = 40.60},
            {x = 900.68, y = 3572.67, z = 33.61},             {x = 338.59, y = 3410.05, z = 36.64},
            {x = 1029.42, y = 3607.01, z = 33.23},

        }
    }

}

Config.PedModels = {
    'a_f_m_beach_01',
    'a_f_m_bevhills_01',
    'a_f_m_bevhills_02',
    'a_f_m_bodybuild_01',
    'a_f_m_business_02',
    'a_f_m_downtown_01',
    'a_f_m_eastsa_01',
    'a_f_m_eastsa_02',
    'a_f_m_fatbla_01',
    'a_f_m_fatwhite_01',
    'a_f_m_ktown_01',
    'a_f_m_ktown_02',
    'a_f_m_prolhost_01',
    'a_f_m_salton_01',
    'a_f_m_skidrow_01',
    'a_f_m_soucent_01',
    'a_f_m_soucent_02',
    'a_f_m_soucentmc_01',
    'a_f_m_tourist_01',
    'a_f_m_tramp_01',
    'a_f_m_trampbeac_01',
    'a_f_o_genstreet_01',
    'a_f_o_indian_01',
    'a_f_o_ktown_01',
    'a_f_o_salton_01',
    'a_f_o_soucent_01',
    'a_f_o_soucent_02',
    'a_f_y_beach_01',
    'a_f_y_bevhills_01',
    'a_f_y_bevhills_02',
    'a_f_y_bevhills_03',
    'a_f_y_bevhills_04',
    'a_f_y_business_01',
    'a_f_y_business_02',
    'a_f_y_business_03',
    'a_f_y_business_04',
    'a_f_y_eastsa_01',
    'a_f_y_eastsa_02',
    'a_f_y_eastsa_03',
    'a_f_y_epsilon_01',
    'a_f_y_fitness_01',
    'a_f_y_fitness_02',
    'a_f_y_genhot_01',
    'a_f_y_golfer_01',
    'a_f_y_hiker_01',
    'a_f_y_hippie_01',
    'a_f_y_hipster_02',
    'a_f_y_hipster_03',
    'a_f_y_hipster_04',
    'a_f_y_indian_01',
    'a_f_y_juggalo_01',
    'a_f_y_runner_01',
    'a_f_y_rurmeth_01',
    'a_f_y_scdressy_01',
    'a_f_y_skater_01',
    'a_f_y_soucent_01',
    'a_f_y_soucent_02',
    'a_f_y_soucent_03',
    'a_f_y_tennis_01',
    'a_f_y_tourist_01',
    'a_f_y_tourist_02',
    'a_f_y_vinewood_01',
    'a_f_y_vinewood_02',
    'a_f_y_vinewood_03',
    'a_f_y_vinewood_04',
    'a_f_y_yoga_01',
    'a_m_m_afriamer_01',
    'a_m_m_beach_01',
    'a_m_m_beach_02',
    'a_m_m_bevhills_01',
    'a_m_m_bevhills_02',
    'a_m_m_business_01',
    'a_m_m_eastsa_01',
    'a_m_m_eastsa_02',
    'a_m_m_farmer_01',
    'a_m_m_fatlatin_01',
    'a_m_m_genfat_01',
    'a_m_m_genfat_02',
    'a_m_m_golfer_01',
    'a_m_m_hasjew_01',
    'a_m_m_hillbilly_01',
    'a_m_m_hillbilly_02',
    'a_m_m_indian_01',
    'a_m_m_ktown_01',
    'a_m_m_malibu_01',
    'a_m_m_mexcntry_01',
    'a_m_m_mexlabor_01',
    'a_m_m_og_boss_01',
    'a_m_m_paparazzi_01',
    'a_m_m_polynesian_01',
    'a_m_m_prolhost_01',
    'a_m_m_rurmeth_01',
    'a_m_m_salton_01',
    'a_m_m_salton_02',
    'a_m_m_salton_03',
    'a_m_m_salton_04',
    'a_m_m_skater_01',
    'a_m_m_skidrow_01',
    'a_m_m_socenlat_01',
    'a_m_m_soucent_01',
    'a_m_m_soucent_02',
    'a_m_m_soucent_03',
    'a_m_m_soucent_04',
    'a_m_m_stlat_02',
    'a_m_m_tennis_01',
    'a_m_m_tourist_01',
    'a_m_m_tramp_01',
    'a_m_m_trampbeac_01',
    'a_m_m_tranvest_01',
    'a_m_m_tranvest_02',
    'a_m_o_acult_02',
    'a_m_o_beach_01',
    'a_m_o_genstreet_01',
    'a_m_o_ktown_01',
    'a_m_o_salton_01',
    'a_m_o_soucent_01',
    'a_m_o_soucent_02',
    'a_m_o_soucent_03',
    'a_m_o_tramp_01',
    'a_m_y_acult_01',
    'a_m_y_acult_02',
    'a_m_y_beach_01',
    'a_m_y_beach_02',
    'a_m_y_beach_03',
    'a_m_y_beachvesp_01',
    'a_m_y_beachvesp_02',
    'a_m_y_bevhills_01',
    'a_m_y_bevhills_02',
    'a_m_y_breakdance_01',
    'a_m_y_busicas_01',
    'a_m_y_business_01',
    'a_m_y_business_03',
    'a_m_y_cyclist_01',
    'a_m_y_dhill_01',
    'a_m_y_downtown_01',
    'a_m_y_eastsa_01',
    'a_m_y_eastsa_02',
    'a_m_y_epsilon_01',
    'a_m_y_epsilon_02',
    'a_m_y_gay_01',
    'a_m_y_gay_02',
    'a_m_y_genstreet_01',
    'a_m_y_genstreet_02',
    'a_m_y_golfer_01',
    'a_m_y_hasjew_01',
    'a_m_y_hiker_01',
    'a_m_y_hippy_01',
    'a_m_y_hipster_01',
    'a_m_y_hipster_02',
    'a_m_y_hipster_03',
    'a_m_y_indian_01',
    'a_m_y_jetski_01',
    'a_m_y_juggalo_01',
    'a_m_y_ktown_01',
    'a_m_y_ktown_02',
    'a_m_y_latino_01',
    'a_m_y_methhead_01',
    'a_m_y_mexthug_01',
    'a_m_y_motox_01',
    'a_m_y_motox_02',
    'a_m_y_musclbeac_01',
    'a_m_y_musclbeac_02',
    'a_m_y_polynesian_01',
    'a_m_y_roadcyc_01',
    'a_m_y_runner_01',
    'a_m_y_runner_02',
    'a_m_y_salton_01',
    'a_m_y_skater_01',
    'a_m_y_skater_02',
    'a_m_y_soucent_01',
    'a_m_y_soucent_02',
    'a_m_y_soucent_03',
    'a_m_y_soucent_04',
    'a_m_y_stbla_01',
    'a_m_y_stbla_02',
    'a_m_y_stlat_01',
    'a_m_y_stwhi_01',
    'a_m_y_stwhi_02',
    'a_m_y_sunbathe_01',
    'a_m_y_surfer_01',
    'a_m_y_vindouche_01',
    'a_m_y_vinewood_01',
    'a_m_y_vinewood_02',
    'a_m_y_vinewood_03',
    'a_m_y_vinewood_04',
    'a_m_y_yoga_01',
    'cs_amandatownley',
    'cs_andreas',
    'cs_ashley',
    'cs_bankman',
    'cs_barry',
    'cs_beverly',
    'cs_brad',
    'cs_carbuyer',
    'cs_casey',
    'cs_chengsr',
    'cs_chrisformage',
    'cs_clay',
    'cs_dale',
    'cs_davenorton',
    'cs_debra',
    'cs_denise',
    'cs_dom',
    'cs_dreyfuss',
    'cs_drfriedlander',
    'cs_fabien',
    'cs_fbisuit_01',
    'cs_floyd',
    'cs_guadalope',
    'cs_gurk',
    'cs_hunter',
    'cs_janet',
    'cs_jewelass',
    'cs_jimmyboston',
    'cs_jimmydisanto',
    'cs_joeminuteman',
    'cs_johnnyklebitz',
    'cs_josef',
    'cs_josh',
    'cs_lamardavis',
    'cs_lazlow',
    'cs_lestercrest',
    'cs_lifeinvad_01',
    'cs_magenta',
    'cs_manuel',
    'cs_marnie',
    'cs_martinmadrazo',
    'cs_maryann',
    'cs_michelle',
    'cs_milton',
    'cs_molly',
    'cs_movpremf_01',
    'cs_movpremmale',
    'cs_mrk',
    'cs_mrs_thornhill',
    'cs_mrsphillips',
    'cs_natalia',
    'cs_nervousron',
    'cs_nigel',
    'cs_old_man1a',
    'cs_old_man2',
    'cs_omega',
    'cs_orleans',
    'cs_paper',
    'cs_patricia',
    'cs_priest',
    'cs_prolsec_02',
    'cs_russiandrunk',
    'cs_siemonyetarian',
    'cs_solomon',
    'cs_stevehains',
    'cs_stretch',
    'cs_tanisha',
    'cs_taocheng',
    'cs_taostranslator',
    'cs_tenniscoach',
    'cs_terry',
    'cs_tom',
    'cs_tomepsilon',
    'cs_tracydisanto',
    'cs_wade',
    'cs_zimbor',
    'csb_abigail',
    'csb_anita',
    'csb_anton',
    'csb_ballasog',
    'csb_bride',
    'csb_burgerdrug',
    'csb_car3guy1',
    'csb_car3guy2',
    'csb_chef',
    'csb_chin_goon',
    'csb_cletus',
    'csb_customer',
    'csb_denise_friend',
    'csb_fos_rep',
    'csb_g',
    'csb_groom',
    'csb_grove_str_dlr',
    'csb_hugh',
    'csb_imran',
    'csb_janitor',
    'csb_maude',
    'csb_mweather',
    'csb_ortega',
    'csb_oscar',
    'csb_porndudes',
    'csb_prologuedriver',
    'csb_prolsec',
    'csb_ramp_gang',
    'csb_ramp_hic',
    'csb_ramp_hipster',
    'csb_ramp_marine',
    'csb_ramp_mex',
    'csb_reporter',
    'csb_roccopelosi',
    'csb_screen_writer',
    'csb_tonya',
    'csb_trafficwarden',
    'csb_vagspeak',
    'g_f_y_ballas_01',
    'g_f_y_families_01',
    'g_f_y_lost_01',
    'g_f_y_vagos_01',
    'g_m_importexport_01',
    'g_m_m_armboss_01',
    'g_m_m_armgoon_01',
    'g_m_m_armlieut_01',
    'g_m_m_chemwork_01',
    'g_m_m_chiboss_01',
    'g_m_m_chicold_01',
    'g_m_m_chigoon_01',
    'g_m_m_chigoon_02',
    'g_m_m_korboss_01',
    'g_m_m_mexboss_01',
    'g_m_m_mexboss_02',
    'g_m_y_armgoon_02',
    'g_m_y_azteca_01',
    'g_m_y_ballaeast_01',
    'g_m_y_ballaorig_01',
    'g_m_y_ballasout_01',
    'g_m_y_famca_01',
    'g_m_y_famdnf_01',
    'g_m_y_famfor_01',
    'g_m_y_korean_01',
    'g_m_y_korean_02',
    'g_m_y_korlieut_01',
    'g_m_y_lost_01',
    'g_m_y_lost_02',
    'g_m_y_lost_03',
    'g_m_y_mexgang_01',
    'g_m_y_mexgoon_01',
    'g_m_y_mexgoon_02',
    'g_m_y_mexgoon_03',
    'g_m_y_pologoon_01',
    'g_m_y_pologoon_02',
    'g_m_y_salvaboss_01',
    'g_m_y_salvagoon_01',
    'g_m_y_salvagoon_02',
    'g_m_y_salvagoon_03',
    'g_m_y_strpunk_01',
    'g_m_y_strpunk_02',
    'hc_driver',
    'hc_gunman',
    'hc_hacker',
    'ig_abigail',
    'ig_amandatownley',
    'ig_andreas',
    'ig_ashley',
    'ig_ballasog',
    'ig_bankman',
    'ig_barry',
    'ig_benny',
    'ig_bestmen',
    'ig_beverly',
    'ig_brad',
    'ig_bride',
    'ig_car3guy1',
    'ig_car3guy2',
    'ig_casey',
    'ig_chef',
    'ig_chengsr',
    'ig_chrisformage',
    'ig_clay',
    'ig_claypain',
    'ig_cletus',
    'ig_dale',
    'ig_davenorton',
    'ig_denise',
    'ig_devin',
    'ig_dom',
    'ig_dreyfuss',
    'ig_drfriedlander',
    'ig_fabien',
    'ig_floyd',
    'ig_g',
    'ig_groom',
    'ig_hao',
    'ig_hunter',
    'ig_janet',
    'ig_jay_norris',
    'ig_jewelass',
    'ig_jimmyboston',
    'ig_jimmydisanto',
    'ig_josef',
    'ig_josh',
    'ig_kerrymcintosh',
    'ig_lamardavis',
    'ig_lazlow',
    'ig_lestercrest',
    'ig_lifeinvad_01',
    'ig_lifeinvad_02',
    'ig_magenta',
    'ig_malc',
    'ig_manuel',
    'ig_marnie',
    'ig_maryann',
    'ig_maude',
    'ig_michelle',
    'ig_milton',
    'ig_molly',
    'ig_mrk',
    'ig_mrs_thornhill',
    'ig_mrsphillips',
    'ig_natalia',
    'ig_nervousron',
    'ig_nigel',
    'ig_old_man1a',
    'ig_old_man2',
    'ig_omega',
    'ig_oneil',
    'ig_orleans',
    'ig_ortega',
    'ig_paper',
    'ig_patricia',
    'ig_priest',
    'ig_prolsec_02',
    'ig_ramp_gang',
    'ig_ramp_hic',
    'ig_ramp_hipster',
    'ig_ramp_mex',
    'ig_roccopelosi',
    'ig_russiandrunk',
    'ig_screen_writer',
    'ig_siemonyetarian',
    'ig_solomon',
    'ig_stevehains',
    'ig_stretch',
    'ig_talina',
    'ig_tanisha',
    'ig_taocheng',
    'ig_taostranslator',
    'ig_tenniscoach',
    'ig_terry',
    'ig_tomepsilon',
    'ig_tonya',
    'ig_tracydisanto',
    'ig_trafficwarden',
    'ig_tylerdix',
    'ig_vagspeak',
    'ig_wade',
    'ig_zimbor',
    'mp_f_boatstaff_01',
    'mp_f_cardesign_01',
    'mp_f_chbar_01',
    'mp_f_cocaine_01',
    'mp_f_counterfeit_01',
    'mp_f_deadhooker',
    'mp_f_execpa_01',
    'mp_f_forgery_01',
    'mp_f_freemode_01',
    'mp_f_helistaff_01',
    'mp_f_meth_01',
    'mp_f_weed_01',
    'mp_g_m_pros_01',
    'mp_headtargets',
    'mp_m_boatstaff_01',
    'mp_m_cocaine_01',
    'mp_m_exarmy_01',
    'mp_m_execpa_01',
    'mp_m_famdd_01',
    'mp_m_fibsec_01',
    'mp_m_freemode_01',
    'mp_m_g_vagfun_01',
    'mp_m_meth_01',
    'mp_m_securoguard_01',
    'mp_m_shopkeep_01',
    'mp_m_waremech_01',
    'mp_m_weed_01',
    'mp_s_m_armoured_01',
    's_f_m_fembarber',
    's_f_m_shop_high',
    's_f_m_sweatshop_01',
    's_f_y_airhostess_01',
    's_f_y_bartender_01',
    's_f_y_baywatch_01',
    's_f_y_factory_01',
    's_f_y_hooker_01',
    's_f_y_hooker_02',
    's_f_y_hooker_03',
    's_f_y_migrant_01',
    's_f_y_movprem_01',
    's_f_y_scrubs_01',
    's_f_y_shop_low',
    's_f_y_shop_mid',
    's_f_y_sweatshop_01',
    's_m_m_ammucountry',
    's_m_m_armoured_01',
    's_m_m_armoured_02',
    's_m_m_autoshop_01',
    's_m_m_autoshop_02',
    's_m_m_bouncer_01',
    's_m_m_chemsec_01',
    's_m_m_ciasec_01',
    's_m_m_cntrybar_01',
    's_m_m_dockwork_01',
    's_m_m_doctor_01',
    's_m_m_gaffer_01',
    's_m_m_gardener_01',
    's_m_m_gentransport',
    's_m_m_hairdress_01',
    's_m_m_highsec_01',
    's_m_m_highsec_02',
    's_m_m_janitor',
    's_m_m_lathandy_01',
    's_m_m_lifeinvad_01',
    's_m_m_linecook',
    's_m_m_lsmetro_01',
    's_m_m_mariachi_01',
    's_m_m_migrant_01',
    's_m_m_movalien_01',
    's_m_m_movprem_01',
    's_m_m_movspace_01',
    's_m_m_paramedic_01',
    's_m_m_pilot_01',
    's_m_m_pilot_02',
    's_m_m_postal_01',
    's_m_m_postal_02',
    's_m_m_scientist_01',
    's_m_m_strperf_01',
    's_m_m_strpreach_01',
    's_m_m_strvend_01',
    's_m_m_trucker_01',
    's_m_m_ups_01',
    's_m_m_ups_02',
    's_m_o_busker_01',
    's_m_y_airworker',
    's_m_y_ammucity_01',
    's_m_y_barman_01',
    's_m_y_baywatch_01',
    's_m_y_chef_01',
    's_m_y_clown_01',
    's_m_y_construct_01',
    's_m_y_construct_02',
    's_m_y_dealer_01',
    's_m_y_devinsec_01',
    's_m_y_dockwork_01',
    's_m_y_doorman_01',
    's_m_y_dwservice_01',
    's_m_y_dwservice_02',
    's_m_y_factory_01',
    's_m_y_fireman_01',
    's_m_y_garbage',
    's_m_y_grip_01',
    's_m_y_mime',
    's_m_y_pestcont_01',
    's_m_y_pilot_01',
    's_m_y_shop_mask',
    's_m_y_strvend_01',
    's_m_y_uscg_01',
    's_m_y_valet_01',
    's_m_y_waiter_01',
    's_m_y_winclean_01',
    's_m_y_xmech_01',
    's_m_y_xmech_02',
    's_m_y_xmech_02_mp',
    'u_f_m_corpse_01',
    'u_f_m_miranda',
    'u_f_m_promourn_01',
    'u_f_o_moviestar',
    'u_f_o_prolhost_01',
    'u_f_y_bikerchic',
    'u_f_y_comjane',
    'u_f_y_corpse_01',
    'u_f_y_hotposh_01',
    'u_f_y_jewelass_01',
    'u_f_y_mistress',
    'u_f_y_poppymich',
    'u_f_y_princess',
    'u_f_y_spyactress',
    'u_m_m_aldinapoli',
    'u_m_m_bankman',
    'u_m_m_bikehire_01',
    'u_m_m_fibarchitect',
    'u_m_m_filmdirector',
    'u_m_m_glenstank_01',
    'u_m_m_griff_01',
    'u_m_m_jesus_01',
    'u_m_m_jewelsec_01',
    'u_m_m_jewelthief',
    'u_m_m_markfost',
    'u_m_m_partytarget',
    'u_m_m_prolsec_01',
    'u_m_m_promourn_01',
    'u_m_m_rivalpap',
    'u_m_m_spyactor',
    'u_m_m_willyfist',
    'u_m_o_finguru_01',
    'u_m_o_taphillbilly',
    'u_m_o_tramp_01',
    'u_m_y_abner',
    'u_m_y_antonb',
    'u_m_y_babyd',
    'u_m_y_baygor',
    'u_m_y_burgerdrug_01',
    'u_m_y_chip',
    'u_m_y_cyclist_01',
    'u_m_y_fibmugger_01',
    'u_m_y_guido_01',
    'u_m_y_gunvend_01',
    'u_m_y_hippie_01',
    'u_m_y_imporage',
    'u_m_y_mani',
    'u_m_y_militarybum',
    'u_m_y_paparazzi',
    'u_m_y_party_01',
    'u_m_y_pogo_01',
    'u_m_y_proldriver_01',
    'u_m_y_rsranger_01',
    'u_m_y_staggrm_01',
    'u_m_y_tattoo_01',
    'u_m_y_zombie_01'
}

-- https://gist.github.com/alexguirre/f3f47f75ddcf617f416f3c8a55ae2227
Config.PedDamagePacks = {
    "BigHitByVehicle",
    "SCR_Torture",
    "SCR_Franklin_finb2",
    "Explosion_Med",
    "Useful_Bits",
    "Explosion_Large",
    "Burnt_Ped_Head_Torso",
    "Car_Crash_Heavy",
    "Fall",
    "HitByVehicle",
    "BigRunOverByVehicle",
    "RunOverByVehicle",
    "SCR_Cougar",
    "TD_SHOTGUN_FRONT_KILL",
    "TD_SHOTGUN_REAR_KILL",
}
